title: da-Kai
email: kaijeschek+github@gmail.com
description: >- 
  My simple Webpage.
baseurl: ""
url: "https://da-kai.github.io/"
github_username:  da-Kai

remote_theme: jekyll/minima
minima:
  skin: auto

plugins:
  - jekyll-feed
  - jekyll-remote-theme
